language: rust
rust:
  - stable
  - beta
  - nightly
env:
  -
  - CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_AVX=
  - CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_SIMD=
matrix:
  allow_failures:
    - rust: nightly
    - env: STAGE=benches
  include:
    - rust: stable
      env: STAGE=benches
    - rust: nightly
      env: STAGE=benches
    - rust: nightly
      env:
        - STAGE=benches
        - CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_AVX=
    - rust: nightly
      env:
        - STAGE=benches
        - CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_SIMD=
cache: cargo

before_script:
  - if [[ "${TRAVIS_RUST_VERSION}" == stable ]]; then
      rustup component add rustfmt;
    fi

script:
  - |
    if [[ -z "$STAGE" ]]; then
    cargo test &&\
    cd testing &&\
    cargo test --features full &&\
    cd ..
    fi
  - |
    if [[ "${TRAVIS_RUST_VERSION}" == "stable" ]]; then
    cargo fmt -- --check &&\
    cd testing &&\
    cargo fmt -- --check &&\
    cd ..
    fi

after_success:
  - |
    if [[ "$STAGE" == "benches" ]] && [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
    cd testing
    cargo bench
    cd ..
    fi
  - |
    if [[ "$STAGE" == "benches" ]] && [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
    cd testing
    cargo bench
    cd ..
    fi
